FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TaskManagementApi.csproj", "./"]
RUN dotnet restore "TaskManagementApi.csproj"
COPY . .
RUN dotnet build "TaskManagementApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaskManagementApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskManagementApi.dll"]